<a href="https://colab.research.google.com/github/jsh-lab/python_programming/blob/main/11%EC%A3%BC%EC%B0%A8_Numpy_%EC%A0%95%EC%83%81%ED%9B%88(2024186854).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
a = np.array([[1,2,3], [4,5,6]])

In [4]:
a.shape

(2, 3)

In [5]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [7]:
print(a[0])

1


In [8]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

In [9]:
a[:3]

array([10,  2,  3])

In [10]:
b = a[3:]
b

array([4, 5, 6])

In [11]:
b[0] = 40
a

array([10,  2,  3, 40,  5,  6])

In [12]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
print(a[1,3])

8


In [15]:
a.ndim

2

In [16]:
a.shape

(3, 4)

In [17]:
len(a.shape) == a.ndim

True

In [18]:
a.size

12

In [19]:
import math
a.size == math.prod(a.shape)

True

In [20]:
a.dtype

dtype('int64')

In [21]:
np.zeros(2)

array([0., 0.])

In [22]:
np.ones(2)

array([1., 1.])

In [25]:
np.empty(2)

array([1., 1.])

In [27]:
np.arange(4)

array([0, 1, 2, 3])

In [28]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [29]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [30]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

In [31]:
arr = np.array([2,1,5,3,7,4,6,8])

In [32]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [33]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6]])
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [36]:
array_example.ndim

3

In [37]:
array_example.size

24

In [38]:
array_example.shape

(3, 2, 4)

In [39]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [40]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [42]:
np.reshape(a, (1, 6), order='C') # shape=(1,6) 으로 지정 시 에러 발생하여 수정

array([[0, 1, 2, 3, 4, 5]])

In [43]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [44]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [45]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [46]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [47]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [48]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [49]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [57]:
data = np.array([1, 2, 3])
print(data[1])

2


In [56]:
data[0:2]

array([1, 2])

In [54]:
data[1:]

array([2, 3])

In [55]:
data[-2:]

array([2, 3])

In [59]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])

[1 2 3 4]


In [60]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [61]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [62]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [63]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [65]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [66]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))


In [67]:
print(a[b])

[1 2 3 4]


In [68]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [69]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [71]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [72]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [73]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [74]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [75]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [76]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [77]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [78]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [79]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [82]:
b2 = a.copy()
b2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [81]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [83]:
data - ones

array([0, 1])

In [84]:
data * data

array([1, 4])

In [85]:
data / data

array([1., 1.])

In [87]:
a = np.array([1, 2, 3, 4])

print(a.sum())

10


In [88]:
b = np.array([[1, 1], [2, 2]])

In [89]:
b.sum(axis=0)

array([3, 3])

In [90]:
b.sum(axis=1)

array([2, 4])

In [91]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [95]:
print(data.max())

2.0


In [96]:
print(data.min())

1.0


In [97]:
print(data.sum())

3.0


In [99]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(a.sum())

4.8595784


In [100]:
print(a.min())

0.05093587


In [101]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [102]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [104]:
print(data[0, 1])

2


In [105]:
print(data[1:3])

[[3 4]
 [5 6]]


In [106]:
print(data[0:2, 0])

[1 3]


In [108]:
print(data.max())

6


In [109]:
print(data.min())

1


In [110]:
print(data.sum())

21


In [112]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [113]:
data.max(axis=0)

array([5, 6])

In [114]:
data.max(axis=1)

array([2, 5, 6])

In [115]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [116]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [118]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [119]:
np.ones(3)

array([1., 1., 1.])

In [120]:
np.zeros(3)

array([0., 0., 0.])

In [122]:
rng = np.random.default_rng()
rng.random(3)

array([0.256654  , 0.38664121, 0.23666447])

In [123]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [124]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [125]:
rng.random((3, 2))

array([[0.74467153, 0.10297236],
       [0.88452514, 0.42641425],
       [0.37123022, 0.02622137]])

In [126]:
rng.integers(5, size=(2, 4))

array([[4, 0, 2, 1],
       [4, 2, 1, 1]])

In [127]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [128]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [129]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [130]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [131]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [132]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [134]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [136]:
print(indices)

[0 1 2]


In [137]:
print(occurrence_count)

[2 1 1]


In [139]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [140]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [141]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [142]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [143]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [146]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(arr)
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [148]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [149]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [150]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [151]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [152]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [153]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [155]:
a1 = x.flatten()
a1[0] = 99
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [156]:
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [158]:
a2 = x.ravel()
a2[0] = 98
print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [159]:
print(a2)

[98  2  3  4  5  6  7  8  9 10 11 12]
